# Practice for Selecting Data with SQL

Run the code below without change to get started.

In [22]:
# Connecting, Libraries, and Data

import sqlite3
conn = sqlite3.connect('data.sqlite')

import pandas as pd

pd.read_sql("""
SELECT *
  FROM products;
""", conn)

,productCode,productName,productLine,productScale,productVendor,productDescription,quantityInStock,buyPrice,MSRP
0,S10_1678,1969 Harley Davidson Ultimate Chopper,Motorcycles,1:10,Min Lin Diecast,"This replica features working kickstand, front...",7933,48.81,95.70
1,S10_1949,1952 Alpine Renault 1300,Classic Cars,1:10,Classic Metal Creations,Turnable front wheels; steering function; deta...,7305,98.58,214.30
2,S10_2016,1996 Moto Guzzi 1100i,Motorcycles,1:10,Highway 66 Mini Classics,"Official Moto Guzzi logos and insignias, saddl...",6625,68.99,118.94
3,S10_4698,2003 Harley-Davidson Eagle Drag Bike,Motorcycles,1:10,Red Start Diecast,"Model features, official Harley Davidson logos...",5582,91.02,193.66
4,S10_4757,1972 Alfa Romeo GTA,Classic Cars,1:10,Motor City Art Classics,Features include: Turnable front wheels; steer...,3252,85.68,136.00
...,...,...,...,...,...,...,...,...,...
105,S700_3505,The Titanic,Ships,1:700,Carousel DieCast Legends,"Completed model measures 19 1/2 inches long, 9...",1956,51.09,100.17
106,S700_3962,The Queen Mary,Ships,1:700,Welly Diecast Productions,Exact replica. Wood and Metal. Many extras inc...,5088,53.63,99.31
107,S700_4002,American Airlines: MD-11S,Planes,1:700,Second Gear Diecast,Polished finish. Exact replia with official lo...,8820,36.27,74.03
108,S72_1253,Boeing X-32A JSF,Planes,1:72,Motor City Art Classics,"10"" Wingspan with retractable landing gears.Co...",4857,32.77,49.66
109,S72_3212,Pont Yacht,Ships,1:72,Unimax Art Galleries,Measures 38 inches Long x 33 3/4 inches High. ...,414,33.30,54.60

1. Select the product name and product code for the products
- Show the last five products

In [23]:
# Your code here
pd.read_sql("""
SELECT productCode, productName
  FROM products;
""", conn).tail()

    productCode                productName
105   S700_3505                The Titanic
106   S700_3962             The Queen Mary
107   S700_4002  American Airlines: MD-11S
108    S72_1253           Boeing X-32A JSF
109    S72_3212                 Pont Yacht

2. Now switch the order of the columns, i.e. show the product code first and then the product name.
- Show the last five products

In [24]:
# Your code here
pd.read_sql("""
SELECT productName, productCode
  FROM products;
""", conn).tail()

                   productName productCode
105                The Titanic   S700_3505
106             The Queen Mary   S700_3962
107  American Airlines: MD-11S   S700_4002
108           Boeing X-32A JSF    S72_1253
109                 Pont Yacht    S72_3212

3. Select the product name and product line
- When the product line is "Planes" keep it as "Planes", otherwise have it as "Not Planes"
- Call this new column "Planes"

In [ ]:
# Your code here
pd.read_sql("""
SELECT productName, productLine,
      CASE
      WHEN productLine = 'Airplane' THEN "Planes"
      ELSE "Not Planes"
      END AS Planes
  FROM products;
""", conn)

                               productName   productLine      Planes
0    1969 Harley Davidson Ultimate Chopper   Motorcycles  Not Planes
1                 1952 Alpine Renault 1300  Classic Cars  Not Planes
2                    1996 Moto Guzzi 1100i   Motorcycles  Not Planes
3     2003 Harley-Davidson Eagle Drag Bike   Motorcycles  Not Planes
4                      1972 Alfa Romeo GTA  Classic Cars  Not Planes
..                                     ...           ...         ...
105                            The Titanic         Ships  Not Planes
106                         The Queen Mary         Ships  Not Planes
107              American Airlines: MD-11S        Planes  Not Planes
108                       Boeing X-32A JSF        Planes  Not Planes
109                             Pont Yacht         Ships  Not Planes

[110 rows x 3 columns]

4. Find the length of the product description for each product.
- Call this new column "description_length"
- Show the first five rows of data

In [25]:
# Your code here
pd.read_sql("""
SELECT length(productDescription) AS description_length
  FROM products;
""", conn).head()

   description_length
0                 230
1                 143
2                 391
3                 494
4                 161

5. Let's change the product vendor to all caps.
- Call this new column "caps_vendor"
- Show the first five rows

In [26]:
# Your code here
pd.read_sql("""
SELECT upper(productVendor) AS caps_vendor
  FROM products;
""", conn).head()

                caps_vendor
0           MIN LIN DIECAST
1   CLASSIC METAL CREATIONS
2  HIGHWAY 66 MINI CLASSICS
3         RED START DIECAST
4   MOTOR CITY ART CLASSICS

6. Let's change the product name to all lowercase.
- Use `lower()` as you did `upper()`
- Call this new column "lower_name"
- Show the first five rows

In [27]:
# Your code here
pd.read_sql("""
SELECT lower(productName) AS lower_name
  FROM products;
""", conn).head()

                              lower_name
0  1969 harley davidson ultimate chopper
1               1952 alpine renault 1300
2                  1996 moto guzzi 1100i
3   2003 harley-davidson eagle drag bike
4                    1972 alfa romeo gta

7. Since all of the product scales are 1:*xxx*, we can take a substring of just the number following the colon.
- The first character following the colon is the third character
- None of the scales are more than 1 to a three digit number

In [29]:
# Your code here
pd.read_sql("""
SELECT substr(productScale, 3,3) AS scale
  FROM products;
""", conn)

    scale
0      10
1      10
2      10
3      10
4      10
..    ...
105   700
106   700
107   700
108    72
109    72

[110 rows x 1 columns]

8. Create a new column "fullName" that has product vendor followed by the product name with a space between
- For example, Min Lin Diecast 1969 Harley Davidson Ultimate Chopper

In [35]:
# Your code here
pd.read_sql("""
SELECT productVendor || " " || productName AS fullName
  FROM products;
""", conn)

                                              fullName
0    Min Lin Diecast 1969 Harley Davidson Ultimate ...
1     Classic Metal Creations 1952 Alpine Renault 1300
2       Highway 66 Mini Classics 1996 Moto Guzzi 1100i
3    Red Start Diecast 2003 Harley-Davidson Eagle D...
4          Motor City Art Classics 1972 Alfa Romeo GTA
..                                                 ...
105               Carousel DieCast Legends The Titanic
106           Welly Diecast Productions The Queen Mary
107      Second Gear Diecast American Airlines: MD-11S
108           Motor City Art Classics Boeing X-32A JSF
109                    Unimax Art Galleries Pont Yacht

[110 rows x 1 columns]

9. Find the difference in price between the MSRP and the buy price.
- Round the difference to the nearest whole number, i.e. as an integer, not floating point
- Call this new column "round_diff"
- Hint: These should all be positive values

In [37]:
# Your code here
pd.read_sql("""
SELECT CAST(round(MSRP - buyPrice) AS INTEGER) AS round_diff
  FROM products;
""", conn)

     round_diff
0            47
1           116
2            50
3           103
4            50
..          ...
105          49
106          46
107          38
108          17
109          21

[110 rows x 1 columns]

In [38]:
conn.close()